services:
  - type: web
    name: rag-habr-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        sync: false
      - key: BASE_URL
        sync: false
      - key: EMBED_BASE_URL
        sync: false
      - key: EMBED_API_KEY
        sync: false
      - key: LLM_MODEL
        value: qwen3-32b
      - key: EMBED_MODEL
        value: bge-m3
      - key: QDRANT_API_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: DEFAULT_TEMPERATURE
        value: "0.0"
      - key: MAX_TOKENS
        value: "512"
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.0"

